### ISSUE TITLE
add(deploy script): Create deploy.js for world-id-state-bridge

### ISSUE THREAD

**Issue by dcbuild3r** [worldcoin/world-id-state-bridge#10]
Create a script that will run inside of a CLI with prompts for all necessary information like RPC URLs, private keys, and smart contract addresses in order to be able to simply deploy the entire stack in conjunction with [`world-id-contracts`](https://github.com/worldcoin/world-id-contracts). 

## TODO

- [x] Create `deploy.js`

## Future TODO
- [ ] Create `integration.js` (tests E2E World ID flow)
- [ ] Test alongside with [`world-id-contracts`](https://github.com/worldcoin/world-id-contracts)
