### ISSUE TITLE
add(storage proof mechanism and external service): Generalize World ID

### ISSUE THREAD

**Issue by dcbuild3r** [worldcoin/world-id-state-bridge#3]
idea: leverage storage proofs of the WorldIDIdentityManager contract on the Ethereum mainnet and run an external relayer service to update all supported target chain WorldID contracts with new WorldID Merkle tree roots and their corresponding timestamps. This approach is easily generalizable to any target chain that supports the cryptography needed to deploy a Semaphore verifier and a storage-proof verifier. For an EVM-based chain, it is a trivial change as contracts for this are already implemented and would only require a <targetChain>WorldID contract deployment and integration to the state relayer service.

### TODO

- [ ] Turn off the state bridge in `world-id-contracts`
- [ ] Build a relayer service that will relay storage proofs of Ethereum mainnet state to destined target networks
- [ ] Implement Storage proof verifier for EVM networks and deploy `<EVM-network>WorldID.sol` contracts.
- [ ] Look into other execution environments like Cairo, Fuel VM, Risc V, etc.

**Comment by dcbuild3r** [comment]
this will most likely not be pursued as storage proofs are looking like a viable alternative. re: [Herodotus](herodotus.dev) integration
