### ISSUE TITLE
Make gas limit in Optimism `sendMessage` variable using `eth_estimateGas` calls

### ISSUE THREAD

**Issue by dcbuild3r** [worldcoin/world-id-state-bridge#55]
### TODO
- [ ] refactor [world-id-contracts](https://github.com/worldcoin/world-id-contracts) to have settable gas limits for all Optimism related calls 
  - [ ] [`sendRootMultichain`](https://github.com/worldcoin/world-id-contracts/blob/df894a94312b3e4f89653b04bdef2fffbdced313/src/WorldIDIdentityManagerImplV1.sol#L675-L682)
  - [ ] [`setRootHistoryExpiry`](https://github.com/worldcoin/world-id-contracts/blob/df894a94312b3e4f89653b04bdef2fffbdced313/src/WorldIDIdentityManagerImplV1.sol#L1007-L1027)
- [ ] refactor functions on [`world-id-state-bridge`](https://github.com/worldcoin/world-id-state-bridge/) to use gas limits from `world-id-contracts`
  - [ ] make `transferOwnershipOptimism` have a variable gas limit (optional).    
- [ ] estimate the gas cost for L2 function call using [`eth_estimateGas`](https://docs.alchemy.com/reference/eth-estimategas) for Optimism Gorli and mainnet (needs RPC - I presume OZ has that functionality built-in but we need to double-check for Optimism).
- [ ] feed the above for all calls of functions that use Optimism's `crossDomainMessenger` [`sendMessage`](https://github.com/ethereum-optimism/optimism/blob/382d38b7d45bcbf73cb5e1e3f28cbd45d24e8a59/packages/contracts-bedrock/contracts/universal/CrossDomainMessenger.sol#L270) function
